// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendEvent.proto

package com.rokid.cloudappclient.protro;

public final class SendEvent {
    private SendEvent() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface SendEventRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.SendEventRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string appId = 1;</code>
         */
        boolean hasAppId();

        /**
         * <code>required string appId = 1;</code>
         */
        java.lang.String getAppId();

        /**
         * <code>required string appId = 1;</code>
         */
        com.google.protobuf.ByteString
        getAppIdBytes();

        /**
         * <code>required string event = 2;</code>
         */
        boolean hasEvent();

        /**
         * <code>required string event = 2;</code>
         */
        java.lang.String getEvent();

        /**
         * <code>required string event = 2;</code>
         */
        com.google.protobuf.ByteString
        getEventBytes();

        /**
         * <code>required string extra = 3;</code>
         */
        boolean hasExtra();

        /**
         * <code>required string extra = 3;</code>
         */
        java.lang.String getExtra();

        /**
         * <code>required string extra = 3;</code>
         */
        com.google.protobuf.ByteString
        getExtraBytes();
    }

    /**
     * Protobuf type {@code proto.SendEventRequest}
     */
    public static final class SendEventRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.SendEventRequest)
            SendEventRequestOrBuilder {
        // Use SendEventRequest.newBuilder() to construct.
        private SendEventRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SendEventRequest() {
            appId_ = "";
            event_ = "";
            extra_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SendEventRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            appId_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            event_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            extra_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.rokid.cloudappclient.protro.SendEvent.SendEventRequest.class, com.rokid.cloudappclient.protro.SendEvent.SendEventRequest.Builder.class);
        }

        private int bitField0_;
        public static final int APPID_FIELD_NUMBER = 1;
        private volatile java.lang.Object appId_;

        /**
         * <code>required string appId = 1;</code>
         */
        public boolean hasAppId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string appId = 1;</code>
         */
        public java.lang.String getAppId() {
            java.lang.Object ref = appId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    appId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string appId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getAppIdBytes() {
            java.lang.Object ref = appId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                appId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EVENT_FIELD_NUMBER = 2;
        private volatile java.lang.Object event_;

        /**
         * <code>required string event = 2;</code>
         */
        public boolean hasEvent() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string event = 2;</code>
         */
        public java.lang.String getEvent() {
            java.lang.Object ref = event_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    event_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string event = 2;</code>
         */
        public com.google.protobuf.ByteString
        getEventBytes() {
            java.lang.Object ref = event_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                event_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EXTRA_FIELD_NUMBER = 3;
        private volatile java.lang.Object extra_;

        /**
         * <code>required string extra = 3;</code>
         */
        public boolean hasExtra() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string extra = 3;</code>
         */
        public java.lang.String getExtra() {
            java.lang.Object ref = extra_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    extra_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string extra = 3;</code>
         */
        public com.google.protobuf.ByteString
        getExtraBytes() {
            java.lang.Object ref = extra_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                extra_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasAppId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasEvent()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasExtra()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, event_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, extra_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, event_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, extra_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.rokid.cloudappclient.protro.SendEvent.SendEventRequest)) {
                return super.equals(obj);
            }
            com.rokid.cloudappclient.protro.SendEvent.SendEventRequest other = (com.rokid.cloudappclient.protro.SendEvent.SendEventRequest) obj;

            boolean result = true;
            result = result && (hasAppId() == other.hasAppId());
            if (hasAppId()) {
                result = result && getAppId()
                        .equals(other.getAppId());
            }
            result = result && (hasEvent() == other.hasEvent());
            if (hasEvent()) {
                result = result && getEvent()
                        .equals(other.getEvent());
            }
            result = result && (hasExtra() == other.hasExtra());
            if (hasExtra()) {
                result = result && getExtra()
                        .equals(other.getExtra());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasAppId()) {
                hash = (37 * hash) + APPID_FIELD_NUMBER;
                hash = (53 * hash) + getAppId().hashCode();
            }
            if (hasEvent()) {
                hash = (37 * hash) + EVENT_FIELD_NUMBER;
                hash = (53 * hash) + getEvent().hashCode();
            }
            if (hasExtra()) {
                hash = (37 * hash) + EXTRA_FIELD_NUMBER;
                hash = (53 * hash) + getExtra().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.rokid.cloudappclient.protro.SendEvent.SendEventRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.SendEventRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.SendEventRequest)
                com.rokid.cloudappclient.protro.SendEvent.SendEventRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.rokid.cloudappclient.protro.SendEvent.SendEventRequest.class, com.rokid.cloudappclient.protro.SendEvent.SendEventRequest.Builder.class);
            }

            // Construct using com.rokid.cloudappclient.protro.SendEvent.SendEventRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                appId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                event_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                extra_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventRequest_descriptor;
            }

            public com.rokid.cloudappclient.protro.SendEvent.SendEventRequest getDefaultInstanceForType() {
                return com.rokid.cloudappclient.protro.SendEvent.SendEventRequest.getDefaultInstance();
            }

            public com.rokid.cloudappclient.protro.SendEvent.SendEventRequest build() {
                com.rokid.cloudappclient.protro.SendEvent.SendEventRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.rokid.cloudappclient.protro.SendEvent.SendEventRequest buildPartial() {
                com.rokid.cloudappclient.protro.SendEvent.SendEventRequest result = new com.rokid.cloudappclient.protro.SendEvent.SendEventRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.appId_ = appId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.event_ = event_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.extra_ = extra_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.rokid.cloudappclient.protro.SendEvent.SendEventRequest) {
                    return mergeFrom((com.rokid.cloudappclient.protro.SendEvent.SendEventRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.rokid.cloudappclient.protro.SendEvent.SendEventRequest other) {
                if (other == com.rokid.cloudappclient.protro.SendEvent.SendEventRequest.getDefaultInstance())
                    return this;
                if (other.hasAppId()) {
                    bitField0_ |= 0x00000001;
                    appId_ = other.appId_;
                    onChanged();
                }
                if (other.hasEvent()) {
                    bitField0_ |= 0x00000002;
                    event_ = other.event_;
                    onChanged();
                }
                if (other.hasExtra()) {
                    bitField0_ |= 0x00000004;
                    extra_ = other.extra_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasAppId()) {
                    return false;
                }
                if (!hasEvent()) {
                    return false;
                }
                return hasExtra();
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.rokid.cloudappclient.protro.SendEvent.SendEventRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.rokid.cloudappclient.protro.SendEvent.SendEventRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object appId_ = "";

            /**
             * <code>required string appId = 1;</code>
             */
            public boolean hasAppId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string appId = 1;</code>
             */
            public java.lang.String getAppId() {
                java.lang.Object ref = appId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        appId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string appId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getAppIdBytes() {
                java.lang.Object ref = appId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    appId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string appId = 1;</code>
             */
            public Builder setAppId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                appId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string appId = 1;</code>
             */
            public Builder clearAppId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                appId_ = getDefaultInstance().getAppId();
                onChanged();
                return this;
            }

            /**
             * <code>required string appId = 1;</code>
             */
            public Builder setAppIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                appId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object event_ = "";

            /**
             * <code>required string event = 2;</code>
             */
            public boolean hasEvent() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string event = 2;</code>
             */
            public java.lang.String getEvent() {
                java.lang.Object ref = event_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        event_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string event = 2;</code>
             */
            public com.google.protobuf.ByteString
            getEventBytes() {
                java.lang.Object ref = event_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    event_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string event = 2;</code>
             */
            public Builder setEvent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                event_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string event = 2;</code>
             */
            public Builder clearEvent() {
                bitField0_ = (bitField0_ & ~0x00000002);
                event_ = getDefaultInstance().getEvent();
                onChanged();
                return this;
            }

            /**
             * <code>required string event = 2;</code>
             */
            public Builder setEventBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                event_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object extra_ = "";

            /**
             * <code>required string extra = 3;</code>
             */
            public boolean hasExtra() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public java.lang.String getExtra() {
                java.lang.Object ref = extra_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        extra_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public com.google.protobuf.ByteString
            getExtraBytes() {
                java.lang.Object ref = extra_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    extra_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public Builder setExtra(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                extra_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public Builder clearExtra() {
                bitField0_ = (bitField0_ & ~0x00000004);
                extra_ = getDefaultInstance().getExtra();
                onChanged();
                return this;
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public Builder setExtraBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                extra_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:proto.SendEventRequest)
        }

        // @@protoc_insertion_point(class_scope:proto.SendEventRequest)
        private static final com.rokid.cloudappclient.protro.SendEvent.SendEventRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.rokid.cloudappclient.protro.SendEvent.SendEventRequest();
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<SendEventRequest>
                PARSER = new com.google.protobuf.AbstractParser<SendEventRequest>() {
            public SendEventRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SendEventRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SendEventRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SendEventRequest> getParserForType() {
            return PARSER;
        }

        public com.rokid.cloudappclient.protro.SendEvent.SendEventRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SendEventResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.SendEventResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string response = 1;</code>
         */
        boolean hasResponse();

        /**
         * <code>required string response = 1;</code>
         */
        java.lang.String getResponse();

        /**
         * <code>required string response = 1;</code>
         */
        com.google.protobuf.ByteString
        getResponseBytes();
    }

    /**
     * Protobuf type {@code proto.SendEventResponse}
     */
    public static final class SendEventResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.SendEventResponse)
            SendEventResponseOrBuilder {
        // Use SendEventResponse.newBuilder() to construct.
        private SendEventResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SendEventResponse() {
            response_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SendEventResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            response_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.rokid.cloudappclient.protro.SendEvent.SendEventResponse.class, com.rokid.cloudappclient.protro.SendEvent.SendEventResponse.Builder.class);
        }

        private int bitField0_;
        public static final int RESPONSE_FIELD_NUMBER = 1;
        private volatile java.lang.Object response_;

        /**
         * <code>required string response = 1;</code>
         */
        public boolean hasResponse() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string response = 1;</code>
         */
        public java.lang.String getResponse() {
            java.lang.Object ref = response_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    response_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string response = 1;</code>
         */
        public com.google.protobuf.ByteString
        getResponseBytes() {
            java.lang.Object ref = response_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                response_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasResponse()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, response_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, response_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.rokid.cloudappclient.protro.SendEvent.SendEventResponse)) {
                return super.equals(obj);
            }
            com.rokid.cloudappclient.protro.SendEvent.SendEventResponse other = (com.rokid.cloudappclient.protro.SendEvent.SendEventResponse) obj;

            boolean result = true;
            result = result && (hasResponse() == other.hasResponse());
            if (hasResponse()) {
                result = result && getResponse()
                        .equals(other.getResponse());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasResponse()) {
                hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getResponse().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.rokid.cloudappclient.protro.SendEvent.SendEventResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.SendEventResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.SendEventResponse)
                com.rokid.cloudappclient.protro.SendEvent.SendEventResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.rokid.cloudappclient.protro.SendEvent.SendEventResponse.class, com.rokid.cloudappclient.protro.SendEvent.SendEventResponse.Builder.class);
            }

            // Construct using com.rokid.cloudappclient.protro.SendEvent.SendEventResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                response_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.rokid.cloudappclient.protro.SendEvent.internal_static_proto_SendEventResponse_descriptor;
            }

            public com.rokid.cloudappclient.protro.SendEvent.SendEventResponse getDefaultInstanceForType() {
                return com.rokid.cloudappclient.protro.SendEvent.SendEventResponse.getDefaultInstance();
            }

            public com.rokid.cloudappclient.protro.SendEvent.SendEventResponse build() {
                com.rokid.cloudappclient.protro.SendEvent.SendEventResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.rokid.cloudappclient.protro.SendEvent.SendEventResponse buildPartial() {
                com.rokid.cloudappclient.protro.SendEvent.SendEventResponse result = new com.rokid.cloudappclient.protro.SendEvent.SendEventResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.response_ = response_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.rokid.cloudappclient.protro.SendEvent.SendEventResponse) {
                    return mergeFrom((com.rokid.cloudappclient.protro.SendEvent.SendEventResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.rokid.cloudappclient.protro.SendEvent.SendEventResponse other) {
                if (other == com.rokid.cloudappclient.protro.SendEvent.SendEventResponse.getDefaultInstance())
                    return this;
                if (other.hasResponse()) {
                    bitField0_ |= 0x00000001;
                    response_ = other.response_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return hasResponse();
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.rokid.cloudappclient.protro.SendEvent.SendEventResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.rokid.cloudappclient.protro.SendEvent.SendEventResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object response_ = "";

            /**
             * <code>required string response = 1;</code>
             */
            public boolean hasResponse() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string response = 1;</code>
             */
            public java.lang.String getResponse() {
                java.lang.Object ref = response_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        response_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string response = 1;</code>
             */
            public com.google.protobuf.ByteString
            getResponseBytes() {
                java.lang.Object ref = response_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    response_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string response = 1;</code>
             */
            public Builder setResponse(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                response_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string response = 1;</code>
             */
            public Builder clearResponse() {
                bitField0_ = (bitField0_ & ~0x00000001);
                response_ = getDefaultInstance().getResponse();
                onChanged();
                return this;
            }

            /**
             * <code>required string response = 1;</code>
             */
            public Builder setResponseBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                response_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:proto.SendEventResponse)
        }

        // @@protoc_insertion_point(class_scope:proto.SendEventResponse)
        private static final com.rokid.cloudappclient.protro.SendEvent.SendEventResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.rokid.cloudappclient.protro.SendEvent.SendEventResponse();
        }

        public static com.rokid.cloudappclient.protro.SendEvent.SendEventResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<SendEventResponse>
                PARSER = new com.google.protobuf.AbstractParser<SendEventResponse>() {
            public SendEventResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SendEventResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SendEventResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SendEventResponse> getParserForType() {
            return PARSER;
        }

        public com.rokid.cloudappclient.protro.SendEvent.SendEventResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_SendEventRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_SendEventRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_SendEventResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_SendEventResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017SendEvent.proto\022\005proto\"?\n\020SendEventReq" +
                        "uest\022\r\n\005appId\030\001 \002(\t\022\r\n\005event\030\002 \002(\t\022\r\n\005ex" +
                        "tra\030\003 \002(\t\"%\n\021SendEventResponse\022\020\n\010respon" +
                        "se\030\001 \002(\tB,\n\037com.rokid.cloudappclient.pro" +
                        "troB\tSendEvent"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_proto_SendEventRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_proto_SendEventRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_SendEventRequest_descriptor,
                new java.lang.String[]{"AppId", "Event", "Extra",});
        internal_static_proto_SendEventResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_proto_SendEventResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_SendEventResponse_descriptor,
                new java.lang.String[]{"Response",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
